package modeling

// renderer_c.go is the C template. It is one file per output section rather than
// one big format string, because the sections have different rules: the register
// accessors follow the access enum, the reset function may only mention documented
// reset values, and the QOM boilerplate differs between sysbus and PCI.
//
// Everything here appends to a strings.Builder and returns nothing, so the shape
// of the generated file is readable top to bottom in renderDeviceSource.

import (
	"fmt"
	"strings"
)

// generatedHeader marks the file for a human and for a later regeneration. It says
// what produced the file and what must not be edited, because the apply step
// refuses to overwrite a file that exists: a hand-edited device would be lost work
// nobody could recover.
const generatedHeader = `/*
 * %s — QEMU device model generated by qemu-agent.
 *
 * Generated from reg-ir.json for device %q on bus %s.
 * Register offsets, widths and access rules come from the extracted register map;
 * anything the documentation did not state is marked TODO below rather than
 * guessed. Re-generating replaces this file, so edit the register map, not this.
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 */
`

// renderDeviceSource assembles the whole .c file. The section order is the order a
// C compiler needs: macros, state, accessors, ops, reset and vmstate all have to
// exist before the class initializer that references them.
func renderDeviceSource(ir RegIR, names deviceNames) (string, error) {
	registers := sortedRegisters(ir)
	var out strings.Builder
	fmt.Fprintf(&out, generatedHeader, names.snake+".c", ir.Device, ir.BusKind)
	writeIncludes(&out, ir)
	writeTypeMacros(&out, ir, names)
	writeRegisterMacros(&out, names, registers)
	writeStateStruct(&out, ir, names, registers)
	writeAccessors(&out, names, registers)
	writeMemoryOps(&out, ir, names)
	writeReset(&out, names, registers)
	writeVMState(&out, names, registers)
	if err := writeConstruction(&out, ir, names); err != nil {
		return "", err
	}
	writeTypeRegistration(&out, ir, names)
	writeNotes(&out, ir)
	return out.String(), nil
}

// writeIncludes lists the headers the generated code actually uses. The set is
// bus-dependent and otherwise fixed: adding "just in case" headers would make the
// output depend on the generator's mood instead of on the IR.
func writeIncludes(out *strings.Builder, ir RegIR) {
	out.WriteString("\n#include \"qemu/osdep.h\"\n")
	if ir.BusKind == BusPCI {
		out.WriteString("#include \"hw/pci/pci_device.h\"\n")
	} else {
		out.WriteString("#include \"hw/sysbus.h\"\n")
	}
	out.WriteString(`#include "hw/irq.h"
#include "hw/qdev-properties.h"
#include "migration/vmstate.h"
#include "qemu/log.h"
#include "qemu/module.h"
#include "qom/object.h"
`)
}

// writeTypeMacros emits the QOM type name and the declaration macro. The type name
// is the dashed spelling because that is what a -device argument and a qtest
// command line use; the cast macro is the upper spelling QOM expects.
func writeTypeMacros(out *strings.Builder, ir RegIR, names deviceNames) {
	parent := "SysBusDevice"
	if ir.BusKind == BusPCI {
		parent = "PCIDevice"
	}
	fmt.Fprintf(out, "\n#define TYPE_%s \"%s\"\n", names.upper, names.dashed)
	fmt.Fprintf(out, "OBJECT_DECLARE_SIMPLE_TYPE(%sState, %s)\n", names.camel, names.upper)
	fmt.Fprintf(out, "\n/* MMIO window: %#x bytes, parent %s. */\n", ir.MMIOSize, parent)
	fmt.Fprintf(out, "#define %s_MMIO_SIZE %#x\n", names.upper, ir.MMIOSize)
}

// writeRegisterMacros emits one offset macro per register plus the shift/mask pair
// of every documented bit field. Field macros are generated even when the model
// wrote no effect text, because a named bit is the most useful thing a reviewer can
// check against the datasheet.
func writeRegisterMacros(out *strings.Builder, names deviceNames, registers []Register) {
	out.WriteString("\n/* Register offsets, from the extracted register map. */\n")
	for _, register := range registers {
		fmt.Fprintf(out, "#define %s_%s %#06x /* %d-bit %s */\n",
			names.upper, strings.ToUpper(register.Name), register.Offset, register.Width, register.Access)
		for _, field := range register.Fields {
			base := fmt.Sprintf("%s_%s_%s", names.upper, strings.ToUpper(register.Name), strings.ToUpper(field.Name))
			fmt.Fprintf(out, "#define %s_SHIFT %d\n", base, field.Bit)
			fmt.Fprintf(out, "#define %s_MASK %#x\n", base, fieldMask(field))
		}
	}
}

// fieldMask is the mask of one bit field, computed rather than templated so a
// 64-bit field cannot silently overflow the shift.
func fieldMask(field Field) uint64 {
	if field.Width >= 64 {
		return ^uint64(0)
	}
	return ((uint64(1) << uint(field.Width)) - 1) << uint(field.Bit)
}

// writeStateStruct emits the device state. Every register gets storage, including
// the read-only ones: a read-only register still has a value the machine model or a
// qtest has to be able to set, and leaving it out would force a later hand edit of
// generated code.
func writeStateStruct(out *strings.Builder, ir RegIR, names deviceNames, registers []Register) {
	fmt.Fprintf(out, "\nstruct %sState {\n", names.camel)
	if ir.BusKind == BusPCI {
		out.WriteString("    PCIDevice parent_obj;\n")
	} else {
		out.WriteString("    SysBusDevice parent_obj;\n")
	}
	out.WriteString("\n    MemoryRegion iomem;\n")
	for _, irq := range ir.Interrupts {
		fmt.Fprintf(out, "    qemu_irq %s; /* index %d */\n", strings.ToLower(irq.Name), irq.Index)
	}
	out.WriteString("\n")
	for _, register := range registers {
		fmt.Fprintf(out, "    %s %s;\n", cTypeOf(register.Width), fieldNameOf(register))
	}
	out.WriteString("};\n")
}

// writeAccessors emits the read and write handlers. This is where the access enum
// becomes behaviour, and the mapping is deliberately conservative:
//
//	ro    readable; a write logs a guest error and changes nothing
//	wo    writable; a read returns 0 and logs a guest error
//	rw    readable and writable
//	w1c   readable; a write clears the bits that were set in the value
//	rsvd  neither; both directions log
//
// A register with a documented side effect gets a TODO comment instead of invented
// code — generating a plausible-looking effect would be the one failure mode a
// reviewer cannot catch by reading the diff.
func writeAccessors(out *strings.Builder, names deviceNames, registers []Register) {
	fmt.Fprintf(out, "\nstatic uint64_t %s_read(void *opaque, hwaddr addr, unsigned size)\n{\n", names.snake)
	fmt.Fprintf(out, "    %sState *s = opaque;\n\n    switch (addr) {\n", names.camel)
	for _, register := range registers {
		macro := fmt.Sprintf("%s_%s", names.upper, strings.ToUpper(register.Name))
		fmt.Fprintf(out, "    case %s:\n", macro)
		switch register.Access {
		case AccessWO, AccessRsvd:
			fmt.Fprintf(out, "        qemu_log_mask(LOG_GUEST_ERROR, \"%%s: read of %s-only register %s\\n\", __func__);\n",
				string(register.Access), register.Name)
			out.WriteString("        return 0;\n")
		default:
			fmt.Fprintf(out, "        return s->%s;\n", fieldNameOf(register))
		}
	}
	out.WriteString("    default:\n")
	out.WriteString("        qemu_log_mask(LOG_UNIMP, \"%s: unimplemented read at 0x%\" HWADDR_PRIx \"\\n\",\n")
	out.WriteString("                      __func__, addr);\n        return 0;\n    }\n}\n")

	fmt.Fprintf(out, "\nstatic void %s_write(void *opaque, hwaddr addr, uint64_t value, unsigned size)\n{\n", names.snake)
	fmt.Fprintf(out, "    %sState *s = opaque;\n\n    switch (addr) {\n", names.camel)
	for _, register := range registers {
		macro := fmt.Sprintf("%s_%s", names.upper, strings.ToUpper(register.Name))
		fmt.Fprintf(out, "    case %s:\n", macro)
		writeRegisterWrite(out, register)
		out.WriteString("        break;\n")
	}
	out.WriteString("    default:\n")
	out.WriteString("        qemu_log_mask(LOG_UNIMP, \"%s: unimplemented write at 0x%\" HWADDR_PRIx \"\\n\",\n")
	out.WriteString("                      __func__, addr);\n        break;\n    }\n}\n")
}

// writeRegisterWrite is the body of one case in the write handler. It is separate
// because the four access kinds are four different statements and inlining them
// would hide the w1c rule inside a switch inside a loop.
func writeRegisterWrite(out *strings.Builder, register Register) {
	field := fieldNameOf(register)
	switch register.Access {
	case AccessRO, AccessRsvd:
		fmt.Fprintf(out, "        qemu_log_mask(LOG_GUEST_ERROR, \"%%s: write to %s register %s\\n\", __func__);\n",
			string(register.Access), register.Name)
		return
	case AccessW1C:
		// Write-1-to-clear is generated rather than TODO'd because it is a
		// mechanical rule; getting it wrong by hand is a classic model bug.
		fmt.Fprintf(out, "        s->%s &= ~(%s)value;\n", field, cTypeOf(register.Width))
	default:
		fmt.Fprintf(out, "        s->%s = (%s)value;\n", field, cTypeOf(register.Width))
	}
	if effect := strings.TrimSpace(register.Effect); effect != "" {
		fmt.Fprintf(out, "        /* TODO: documented side effect — %s */\n", oneLine(effect))
	}
}

// oneLine flattens text that is about to become a C comment. A newline inside a
// /* */ comment is legal but a "*/" is not, so both are neutralized: generated code
// that does not parse would be a generator bug reported as a build failure.
func oneLine(raw string) string {
	collapsed := strings.Join(strings.Fields(raw), " ")
	return strings.ReplaceAll(collapsed, "*/", "* /")
}

// writeMemoryOps emits the MemoryRegionOps. Access sizes are taken from the widest
// register in the map rather than fixed at 4, because a device with a 64-bit
// register that rejects 8-byte accesses is broken in a way that only shows up under
// a guest driver.
func writeMemoryOps(out *strings.Builder, ir RegIR, names deviceNames) {
	widest := 1
	for _, register := range ir.Registers {
		if size := register.Width / 8; size > widest {
			widest = size
		}
	}
	fmt.Fprintf(out, "\nstatic const MemoryRegionOps %s_ops = {\n", names.snake)
	fmt.Fprintf(out, "    .read = %s_read,\n    .write = %s_write,\n", names.snake, names.snake)
	out.WriteString("    .endianness = DEVICE_LITTLE_ENDIAN,\n")
	fmt.Fprintf(out, "    .valid.min_access_size = 1,\n    .valid.max_access_size = %d,\n", widest)
	out.WriteString("};\n")
}

// writeReset emits the reset handler. Only documented reset values are assigned:
// a register whose reset value the datasheet did not state gets a TODO line, so the
// generated device says "unknown" in code the same way open-questions.md says it in
// prose. Defaulting to zero here is the exact mistake invariant 5 forbids.
func writeReset(out *strings.Builder, names deviceNames, registers []Register) {
	fmt.Fprintf(out, "\nstatic void %s_reset(DeviceState *dev)\n{\n", names.snake)
	fmt.Fprintf(out, "    %sState *s = %s(dev);\n\n", names.camel, names.upper)
	documented := 0
	for _, register := range registers {
		field := fieldNameOf(register)
		if register.Reset != nil {
			fmt.Fprintf(out, "    s->%s = %#x;\n", field, *register.Reset)
			documented++
			continue
		}
		fmt.Fprintf(out, "    s->%s = 0; /* TODO: reset value of %s is undocumented */\n", field, register.Name)
	}
	if documented == 0 {
		out.WriteString("    /* TODO: no reset value in this map is documented; see open-questions.md */\n")
	}
	out.WriteString("}\n")
}

// writeVMState emits the migration description. Every register is listed, in the
// same order as the struct, because a missing field is a migration bug that only
// appears on a live guest — and the version is pinned at 1 for the same reason the
// struct name is stable.
func writeVMState(out *strings.Builder, names deviceNames, registers []Register) {
	fmt.Fprintf(out, "\nstatic const VMStateDescription vmstate_%s = {\n", names.snake)
	fmt.Fprintf(out, "    .name = TYPE_%s,\n    .version_id = 1,\n    .minimum_version_id = 1,\n", names.upper)
	out.WriteString("    .fields = (const VMStateField[]) {\n")
	for _, register := range registers {
		fmt.Fprintf(out, "        VMSTATE_UINT%d(%s, %sState),\n",
			register.Width, fieldNameOf(register), names.camel)
	}
	out.WriteString("        VMSTATE_END_OF_LIST()\n    },\n};\n")
}

// writeConstruction emits the part that differs per bus: a sysbus device publishes
// its MMIO region and IRQ lines from instance_init, while a PCI device registers a
// BAR from realize. The two are separate functions rather than one with flags,
// because mixing them is how a generated PCI device ends up calling
// sysbus_init_mmio.
func writeConstruction(out *strings.Builder, ir RegIR, names deviceNames) error {
	switch ir.BusKind {
	case BusSysbus:
		writeSysbusConstruction(out, ir, names)
		return nil
	case BusPCI:
		writePCIConstruction(out, ir, names)
		return nil
	default:
		// Unreachable for a validated IR; returned rather than ignored so a new bus
		// kind cannot silently render a sysbus device.
		return fmt.Errorf("%w: no C template for bus %q", ErrStageUnavailable, ir.BusKind)
	}
}

func writeSysbusConstruction(out *strings.Builder, ir RegIR, names deviceNames) {
	fmt.Fprintf(out, "\nstatic void %s_init(Object *obj)\n{\n", names.snake)
	fmt.Fprintf(out, "    %sState *s = %s(obj);\n", names.camel, names.upper)
	out.WriteString("    SysBusDevice *sbd = SYS_BUS_DEVICE(obj);\n\n")
	fmt.Fprintf(out, "    memory_region_init_io(&s->iomem, obj, &%s_ops, s,\n", names.snake)
	fmt.Fprintf(out, "                          TYPE_%s, %s_MMIO_SIZE);\n", names.upper, names.upper)
	out.WriteString("    sysbus_init_mmio(sbd, &s->iomem);\n")
	for _, irq := range ir.Interrupts {
		fmt.Fprintf(out, "    sysbus_init_irq(sbd, &s->%s);\n", strings.ToLower(irq.Name))
	}
	out.WriteString("}\n")

	fmt.Fprintf(out, "\nstatic void %s_class_init(ObjectClass *klass, const void *data)\n{\n", names.snake)
	out.WriteString("    DeviceClass *dc = DEVICE_CLASS(klass);\n\n")
	fmt.Fprintf(out, "    dc->desc = \"%s (generated by qemu-agent)\";\n", names.dashed)
	fmt.Fprintf(out, "    dc->vmsd = &vmstate_%s;\n", names.snake)
	fmt.Fprintf(out, "    device_class_set_legacy_reset(dc, %s_reset);\n", names.snake)
	out.WriteString("    set_bit(DEVICE_CATEGORY_MISC, dc->categories);\n}\n")
}

func writePCIConstruction(out *strings.Builder, ir RegIR, names deviceNames) {
	fmt.Fprintf(out, "\nstatic void %s_realize(PCIDevice *pci_dev, Error **errp)\n{\n", names.snake)
	fmt.Fprintf(out, "    %sState *s = %s(pci_dev);\n\n", names.camel, names.upper)
	fmt.Fprintf(out, "    memory_region_init_io(&s->iomem, OBJECT(s), &%s_ops, s,\n", names.snake)
	fmt.Fprintf(out, "                          TYPE_%s, %s_MMIO_SIZE);\n", names.upper, names.upper)
	out.WriteString("    pci_register_bar(pci_dev, 0, PCI_BASE_ADDRESS_SPACE_MEMORY, &s->iomem);\n")
	if len(ir.Interrupts) > 0 {
		out.WriteString("    /* TODO: wire the interrupt(s) below to MSI or INTx as the datasheet requires. */\n")
	}
	out.WriteString("}\n")

	fmt.Fprintf(out, "\nstatic void %s_class_init(ObjectClass *klass, const void *data)\n{\n", names.snake)
	out.WriteString("    DeviceClass *dc = DEVICE_CLASS(klass);\n")
	out.WriteString("    PCIDeviceClass *k = PCI_DEVICE_CLASS(klass);\n\n")
	fmt.Fprintf(out, "    k->realize = %s_realize;\n", names.snake)
	out.WriteString("    /* TODO: set k->vendor_id, k->device_id and k->class_id from the datasheet. */\n")
	fmt.Fprintf(out, "    dc->desc = \"%s (generated by qemu-agent)\";\n", names.dashed)
	fmt.Fprintf(out, "    dc->vmsd = &vmstate_%s;\n", names.snake)
	fmt.Fprintf(out, "    device_class_set_legacy_reset(dc, %s_reset);\n", names.snake)
	out.WriteString("    set_bit(DEVICE_CATEGORY_MISC, dc->categories);\n}\n")
}

// writeTypeRegistration emits the TypeInfo and the type_init hook. The PCI variant
// declares the conventional-PCI interface, without which the device cannot be
// plugged into a normal PCI bus.
func writeTypeRegistration(out *strings.Builder, ir RegIR, names deviceNames) {
	fmt.Fprintf(out, "\nstatic const TypeInfo %s_info = {\n", names.snake)
	fmt.Fprintf(out, "    .name = TYPE_%s,\n", names.upper)
	if ir.BusKind == BusPCI {
		out.WriteString("    .parent = TYPE_PCI_DEVICE,\n")
	} else {
		out.WriteString("    .parent = TYPE_SYS_BUS_DEVICE,\n")
	}
	fmt.Fprintf(out, "    .instance_size = sizeof(%sState),\n", names.camel)
	if ir.BusKind != BusPCI {
		fmt.Fprintf(out, "    .instance_init = %s_init,\n", names.snake)
	}
	fmt.Fprintf(out, "    .class_init = %s_class_init,\n", names.snake)
	if ir.BusKind == BusPCI {
		out.WriteString("    .interfaces = (const InterfaceInfo[]) {\n")
		out.WriteString("        { INTERFACE_CONVENTIONAL_PCI_DEVICE },\n        { },\n    },\n")
	}
	out.WriteString("};\n")
	fmt.Fprintf(out, "\nstatic void %s_register_types(void)\n{\n    type_register_static(&%s_info);\n}\n",
		names.snake, names.snake)
	fmt.Fprintf(out, "\ntype_init(%s_register_types)\n", names.snake)
}

// writeNotes appends the IR's notes as a trailing comment block. They are the
// datasheet's gaps in the model's own words, and putting them in the file — not only
// in open-questions.md — means the person who later hand-completes this device reads
// them without going back to the project.
func writeNotes(out *strings.Builder, ir RegIR) {
	if len(ir.Notes) == 0 {
		return
	}
	out.WriteString("\n/*\n * Notes carried over from the register map:\n")
	for _, note := range ir.Notes {
		fmt.Fprintf(out, " *  - %s\n", oneLine(note))
	}
	out.WriteString(" */\n")
}

// renderMesonFragment is the build-system half. It is an append, so it is a
// self-contained line plus a comment saying which device it belongs to: a reviewer
// looking at hw/misc/meson.build later has to be able to tell where it came from.
func renderMesonFragment(names deviceNames) string {
	return fmt.Sprintf(`
# %s — added by qemu-agent
system_ss.add(when: 'CONFIG_%s', if_true: files('%s.c'))
`, names.dashed, names.config, names.snake)
}

// renderKconfigFragment declares the config symbol the meson line depends on. The
// PCI variant selects PCI, because a device whose parent type is TYPE_PCI_DEVICE
// cannot build in a configuration without it.
func renderKconfigFragment(ir RegIR, names deviceNames) string {
	var out strings.Builder
	fmt.Fprintf(&out, "\n# %s — added by qemu-agent\nconfig %s\n    bool\n",
		names.dashed, names.config)
	if ir.BusKind == BusPCI {
		out.WriteString("    select PCI\n")
	}
	return out.String()
}
